[package]
name = "cli_custom_functions"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
csv = "1.1.6"
rand = "0.8.5"

[lib]
name = "lib_functions"
path = "src/lib.rs"
