[package]
name = "csv-filter"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
tokio = { version = "1", features = ["full"] }
aws-sdk-s3 = "0.0.26-alpha"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
